name: Trigger n8n on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  call-n8n:
    runs-on: ubuntu-latest

    steps:
      - name: Send PR data to n8n via HTTP POST
        run: |
          curl -X POST https://alesha-unconvertible-trey.ngrok-free.dev/webhook/github-pr \
            -H "Content-Type: application/json" \
            -d '{
              "action": "${{ github.event.action }}",
              "title": "${{ github.event.pull_request.title }}",
              "branch": "${{ github.event.pull_request.head.ref }}",
              "base": "${{ github.event.pull_request.base.ref }}",
              "repo": "${{ github.repository }}",
              "sender": "${{ github.actor }}"
            }'
